server:
  port: 8082 #Eureka Server地址
spring:
  application:
    name: client2 #应用名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
      prefer-ip-address: true
      instanceId: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true